repos:
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: ['--ignore-missing-imports', '--install-types', '--non-interactive', '--disable-error-code=name-defined']
        additional_dependencies:
          - strawberry-graphql
