version: '3.8'

services:
  web:  # Renamed service to "web"
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://user:password@db:5432/product_db
      - OFFERS_SERVICE_URL=https://python.exercise.applifting.cz/api/v1
      - REFRESH_TOKEN=99f15cd2-c064-4087-b74a-8b35aff72418
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=5000
      - FLASK_DEBUG=true
      - API_BASE_URL=http://0.0.0.0:5000/api
      - DATABASE_URL_LOCAL=postgresql://user:password@0.0.0.0:5437/product_db
      - START_SCHEDULER_ON_STARTUP = True
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 60s
      retries: 3
    # command: >

    #   #!/bin/sh
    #   poetry run flask db upgrade &&
    #   exec poetry run gunicorn -b :5000 --access-logfile - --error-logfile - "app:app"
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'product_db'
    ports:
      - "5437:5432"
