global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'web_app'
    static_configs:
      - targets: ['web:5000']
    metrics_path: '/metrics'

  - job_name: 'postgresql'
    static_configs:
      - targets: ['db:5432']
    metrics_path: '/metrics'
